% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={PCA and Outlier Analysis on Machines Data},
  pdfauthor={Grupo},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{PCA and Outlier Analysis on Machines Data}
\author{Grupo}
\date{2025-12-09}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}

\section{Introduction}\label{introduction}

This report walks through an analysis of a subset of the
\texttt{machines} data from the \texttt{rrcov} package (rows
\textbf{hp-3000/64} to \textbf{ibm-4331-2}).

\subsection{Objectives of the study}\label{objectives-of-the-study}

\begin{itemize}
\tightlist
\item
  Describe the variables using classical and robust summaries,
  Mahalanobis distances and graphical tools, and comment on the main
  patterns in the data.
\item
  Apply PCA on the original and standardized scales, compare the
  proportion of explained variance and interpret the retained components
  (keeping at least 95\% of total variance).
\item
  Introduce a single atypical observation and compare the impact on
  classical PCA versus a robust PCA based on the MCD estimate.
\end{itemize}

\section{Study plan (at a glance)}\label{study-plan-at-a-glance}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  Inspect the data: structure, variable meaning, rough scales.\\
\item
  Classical and robust summaries to see skew/tails and dependence
  (covariance, distances).\\
\item
  PCA on raw vs standardized variables; compare variance explained and
  loadings; pick components reaching 95\%.\\
\item
  Inject one outlier and compare classical vs robust PCA to illustrate
  sensitivity.\\
\item
  Conclude and state a recommendation for which PCA to report and why.
\end{enumerate}

\section{Setup and data}\label{setup-and-data}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# install.packages(c("rrcov", "robustbase"), repos = "https://cloud.r{-}project.org")  \# install if missing}
\FunctionTok{library}\NormalTok{(rrcov)          }\CommentTok{\# robust multivariate methods (PCA, covariance)}
\FunctionTok{library}\NormalTok{(robustbase)     }\CommentTok{\# robust basics (MCD, etc.)}

\FunctionTok{data}\NormalTok{(machines)          }\CommentTok{\# load the machines dataset}
\NormalTok{machines\_sub }\OtherTok{\textless{}{-}}\NormalTok{ machines[}\DecValTok{71}\SpecialCharTok{:}\DecValTok{111}\NormalTok{, ]                  }\CommentTok{\# slice rows hp{-}3000/64 ... ibm{-}4331{-}2}
\NormalTok{machines\_sub}\SpecialCharTok{$}\NormalTok{machine }\OtherTok{\textless{}{-}} \FunctionTok{rownames}\NormalTok{(machines\_sub)      }\CommentTok{\# store machine names for labeling}
\FunctionTok{rownames}\NormalTok{(machines\_sub) }\OtherTok{\textless{}{-}} \ConstantTok{NULL}                      \CommentTok{\# drop row names to avoid confusion}

\NormalTok{n\_obs }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(machines\_sub)                         }\CommentTok{\# count observations}
\NormalTok{n\_vars }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(machines\_sub) }\SpecialCharTok{{-}} \DecValTok{1}                    \CommentTok{\# count numeric variables (exclude machine names)}

\FunctionTok{head}\NormalTok{(machines\_sub, }\DecValTok{3}\NormalTok{)                               }\CommentTok{\# peek at the first rows}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  MYCT MMIN MMAX CACH CHMIN CHMAX PRP ERP     machine
1   75 2000 8000    8     3    24  62  47  hp-3000/64
2   75 3000 8000    8     3    48  64  54  hp-3000/88
3  175  256 2000    0     3    24  22  20 hp-3000/iii
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# summarize each variable (min/mean/median/max/quartiles)}
\FunctionTok{summary}\NormalTok{(machines\_sub)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
      MYCT             MMIN            MMAX            CACH      
 Min.   :  26.0   Min.   :   96   Min.   :  512   Min.   : 0.00  
 1st Qu.: 140.0   1st Qu.:  768   1st Qu.: 3000   1st Qu.: 0.00  
 Median : 300.0   Median : 1000   Median : 4000   Median : 4.00  
 Mean   : 322.7   Mean   : 2435   Mean   : 9812   Mean   :10.41  
 3rd Qu.: 330.0   3rd Qu.: 2000   3rd Qu.:12000   3rd Qu.: 8.00  
 Max.   :1100.0   Max.   :16000   Max.   :32000   Max.   :64.00  
     CHMIN            CHMAX             PRP           ERP        
 Min.   : 1.000   Min.   :  1.00   Min.   :  6   Min.   : 15.00  
 1st Qu.: 1.000   1st Qu.:  2.00   1st Qu.: 22   1st Qu.: 23.00  
 Median : 1.000   Median : 20.00   Median : 38   Median : 30.00  
 Mean   : 3.171   Mean   : 20.39   Mean   : 80   Mean   : 69.34  
 3rd Qu.: 4.000   3rd Qu.: 24.00   3rd Qu.: 66   3rd Qu.: 57.00  
 Max.   :16.000   Max.   :112.00   Max.   :465   Max.   :361.00  
   machine         
 Length:41         
 Class :character  
 Mode  :character  
                   
                   
                   
\end{verbatim}

\section{Data description}\label{data-description}

\begin{itemize}
\tightlist
\item
  Observations: 41 machines; numeric variables: 8.
\item
  Variables (all numeric):

  \begin{itemize}
  \tightlist
  \item
    \texttt{MYCT} cycle time (ns), \texttt{MMIN} min memory (KB),
    \texttt{MMAX} max memory (KB), \texttt{CACH} cache (KB),\\
  \item
    \texttt{CHMIN} min channels, \texttt{CHMAX} max channels,
    \texttt{PRP} published perf, \texttt{ERP} estimated perf.\\
  \end{itemize}
\item
  Machine IDs live in \texttt{machine} (formerly row names). Use them
  for labels, not for analysis.
\end{itemize}

Historically, these data come from the Computer Hardware dataset
describing mainframe computers from the 1970s--1980s. Each row
corresponds to a specific machine model, with hardware specifications
(cycle time, memory, cache, number of I/O channels) and two performance
measures. The variables \texttt{CHMIN} and \texttt{CHMAX} denote the
minimum and maximum number of I/O channels the system can be configured
with, so they reflect scalability for small versus large installations.

To make the variables more concrete, consider two machines in our
subset:

\begin{itemize}
\tightlist
\item
  \texttt{hp-3000/iii} has \texttt{MYCT\ =\ 175} ns (slower CPU),
  \texttt{MMIN\ =\ 256} KB and \texttt{MMAX\ =\ 2000} KB of memory, no
  cache and between 3 and 24 channels (\texttt{CHMIN\ =\ 3},
  \texttt{CHMAX\ =\ 24}), with published performance
  \texttt{PRP\ =\ 22}. This is a relatively modest system in both memory
  and performance.
\item
  \texttt{ibm-3081} has \texttt{MYCT\ =\ 26} ns (much faster),
  \texttt{MMIN\ =\ 16000} KB and \texttt{MMAX\ =\ 32000} KB of memory,
  cache \texttt{CACH\ =\ 64}, between 16 and 24 channels, and
  \texttt{PRP\ =\ 465}. It represents a high-end configuration with far
  greater memory and throughput capability.
\end{itemize}

These contrasts illustrate how larger memory, more channels and lower
cycle time are associated with higher performance measures, which is
precisely the multivariate relationship we summarise with PCA in later
sections.

Before any formal analysis, these hardware considerations give us clear
prior expectations: we anticipate a strong negative association between
\texttt{MYCT} and the performance variables, and positive associations
between \texttt{MMIN}, \texttt{MMAX}, \texttt{CACH}, the channel counts
and \texttt{PRP}/\texttt{ERP}. We also expect \texttt{PRP} and
\texttt{ERP} to be highly correlated, since both are measuring the same
underlying notion of computing power. In terms of PCA, a natural prior
is that the leading standardized component will reflect an overall
``size/performance'' level combining memory, cache and performance,
while a secondary component may capture differences in channel
configuration relative to speed.

Quick look at the machine names:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(machines\_sub}\SpecialCharTok{$}\NormalTok{machine, }\DecValTok{5}\NormalTok{)                       }\CommentTok{\# show first few machine IDs}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "hp-3000/64"  "hp-3000/88"  "hp-3000/iii" "harris-100"  "harris-300" 
\end{verbatim}

Helper functions for trimmed/winsorized means and total/generalized
variance:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{winsor\_mean }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x, }\AttributeTok{probs =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.05}\NormalTok{, }\FloatTok{0.95}\NormalTok{)) \{}
\NormalTok{  qs }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(x, probs, }\AttributeTok{names =} \ConstantTok{FALSE}\NormalTok{)           }\CommentTok{\# lower/upper cutoffs}
  \FunctionTok{mean}\NormalTok{(}\FunctionTok{pmin}\NormalTok{(}\FunctionTok{pmax}\NormalTok{(x, qs[}\DecValTok{1}\NormalTok{]), qs[}\DecValTok{2}\NormalTok{]))                 }\CommentTok{\# clamp extremes then average}
\NormalTok{\}}

\NormalTok{total\_variance }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(S) }\FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(S))          }\CommentTok{\# sum of variances (trace)}
\NormalTok{generalized\_variance }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(S) }\FunctionTok{determinant}\NormalTok{(S, }\AttributeTok{logarithm =} \ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{$}\NormalTok{modulus  }\CommentTok{\# log{-}determinant}
\end{Highlighting}
\end{Shaded}

\section{Exploratory summaries}\label{exploratory-summaries}

\subsection{Classical vs robust
location/scale}\label{classical-vs-robust-locationscale}

Focus: see how skew and heavy tails affect means; compare to
median/trimmed/winsor/MAD.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{num\_vars }\OtherTok{\textless{}{-}}\NormalTok{ machines\_sub[ , }\FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(machines\_sub), }\StringTok{"machine"}\NormalTok{)]  }\CommentTok{\# numeric{-}only data}

\NormalTok{stat\_table }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(                              }\CommentTok{\# assemble summary table}
  \AttributeTok{variable =} \FunctionTok{names}\NormalTok{(num\_vars),                     }\CommentTok{\# variable name}
  \AttributeTok{mean =} \FunctionTok{sapply}\NormalTok{(num\_vars, mean),                  }\CommentTok{\# arithmetic mean}
  \AttributeTok{median =} \FunctionTok{sapply}\NormalTok{(num\_vars, median),              }\CommentTok{\# median}
  \AttributeTok{trimmed\_mean =} \FunctionTok{sapply}\NormalTok{(num\_vars, mean, }\AttributeTok{trim =} \FloatTok{0.1}\NormalTok{),  }\CommentTok{\# 10\% trimmed mean}
  \AttributeTok{winsor\_mean =} \FunctionTok{sapply}\NormalTok{(num\_vars, winsor\_mean),    }\CommentTok{\# 5–95 winsorized mean}
  \AttributeTok{sd =} \FunctionTok{sapply}\NormalTok{(num\_vars, sd),                      }\CommentTok{\# standard deviation}
  \AttributeTok{var =} \FunctionTok{sapply}\NormalTok{(num\_vars, var),                    }\CommentTok{\# variance}
  \AttributeTok{mad =} \FunctionTok{sapply}\NormalTok{(num\_vars, mad)                     }\CommentTok{\# median absolute deviation}
\NormalTok{)}

\NormalTok{stat\_table                                        }\CommentTok{\# show table}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
      variable        mean median trimmed_mean winsor_mean           sd
MYCT      MYCT  322.707317    300   276.575758  312.951220   301.747845
MMIN      MMIN 2435.121951   1000  1542.787879 2050.341463  3563.887261
MMAX      MMAX 9811.707317   4000  8212.121212 9829.268293 10584.538663
CACH      CACH   10.414634      4     6.151515   10.414634    17.915043
CHMIN    CHMIN    3.170732      1     2.484848    2.878049     3.390446
CHMAX    CHMAX   20.390244     20    16.606061   18.731707    22.381776
PRP        PRP   80.000000     38    54.575758   71.048780   108.868728
ERP        ERP   69.341463     30    50.393939   62.829268    84.751286
               var       mad
MYCT  9.105176e+04  237.2160
MMIN  1.270129e+07 1103.0544
MMAX  1.120325e+08 4447.8000
CACH  3.209488e+02    5.9304
CHMIN 1.149512e+01    0.0000
CHMAX 5.009439e+02   20.7564
PRP   1.185240e+04   32.6172
ERP   7.182780e+03   17.7912
\end{verbatim}

From this table we can see, for each variable, how sensitive the mean is
to extreme values by comparing it with the median, the trimmed mean and
the winsorized mean. Large differences between the mean and the robust
summaries indicate asymmetric or heavy-tailed behaviour. The MAD column
complements the standard deviation by providing a scale measure that is
less influenced by atypical machines.

\subsection{Covariance, total and generalized
variance}\label{covariance-total-and-generalized-variance}

These give a sense of joint spread; generalized variance is the
log-determinant (stable on the log scale).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{S\_classic }\OtherTok{\textless{}{-}} \FunctionTok{cov}\NormalTok{(num\_vars)                          }\CommentTok{\# classical covariance matrix}
\NormalTok{total\_var }\OtherTok{\textless{}{-}} \FunctionTok{total\_variance}\NormalTok{(S\_classic)              }\CommentTok{\# total variance (trace)}
\NormalTok{gen\_var\_log }\OtherTok{\textless{}{-}} \FunctionTok{generalized\_variance}\NormalTok{(S\_classic)      }\CommentTok{\# log generalized variance}

\FunctionTok{list}\NormalTok{(}
  \AttributeTok{covariance\_matrix =}\NormalTok{ S\_classic,                  }\CommentTok{\# covariance matrix}
  \AttributeTok{total\_variance =}\NormalTok{ total\_var,                     }\CommentTok{\# total variance}
  \AttributeTok{generalized\_variance\_log =}\NormalTok{ gen\_var\_log          }\CommentTok{\# log generalized variance}
\NormalTok{)                                                  }\CommentTok{\# print results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
$covariance_matrix
               MYCT         MMIN         MMAX         CACH        CHMIN
MYCT     91051.7622  -432377.463  -1609363.49  -2092.07561  -440.823780
MMIN   -432377.4634 12701292.410  24690893.74  41241.87317  8756.653659
MMAX  -1609363.4878 24690893.737 112032458.71 138025.22439 17389.951220
CACH     -2092.0756    41241.873    138025.22    320.94878    33.402439
CHMIN     -440.8238     8756.654     17389.95     33.40244    11.495122
CHMAX    -2618.3579     3924.551     92296.42    110.28415     4.831707
PRP     -15881.2000   359417.800    968283.00   1556.55000   277.225000
ERP     -11618.7226   263724.107    820483.00   1253.72988   187.415244
             CHMAX        PRP         ERP
MYCT  -2618.357927 -15881.200 -11618.7226
MMIN   3924.551220 359417.800 263724.1073
MMAX  92296.417073 968283.000 820483.0024
CACH    110.284146   1556.550   1253.7299
CHMIN     4.831707    277.225    187.4152
CHMAX   500.943902    442.150    481.2134
PRP     442.150000  11852.400   8981.1000
ERP     481.213415   8981.100   7182.7805

$total_variance
[1] 124844671

$generalized_variance_log
[1] 67.78829
attr(,"logarithm")
[1] TRUE
\end{verbatim}

\subsection{Mahalanobis distances
(classical)}\label{mahalanobis-distances-classical}

Note: the squared Mahalanobis distance is approximately chi-square with
\texttt{p} degrees of freedom (\texttt{p} = number of numeric
variables). Using the 97.5th percentile cutoff marks points that are
unusually far from the multivariate center (potential joint outliers).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{md\_classic }\OtherTok{\textless{}{-}} \FunctionTok{mahalanobis}\NormalTok{(}
\NormalTok{  num\_vars,                              }\CommentTok{\# data matrix}
  \AttributeTok{center =} \FunctionTok{colMeans}\NormalTok{(num\_vars),           }\CommentTok{\# classic mean vector}
  \AttributeTok{cov =}\NormalTok{ S\_classic                        }\CommentTok{\# classic covariance matrix}
\NormalTok{)}
\NormalTok{cutoff }\OtherTok{\textless{}{-}} \FunctionTok{qchisq}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =} \FunctionTok{ncol}\NormalTok{(num\_vars))  }\CommentTok{\# 97.5\% chi{-}square threshold}

\CommentTok{\# Robust (MCD) Mahalanobis distances}
\NormalTok{cmcd }\OtherTok{\textless{}{-}}\NormalTok{ robustbase}\SpecialCharTok{::}\FunctionTok{covMcd}\NormalTok{(num\_vars)     }\CommentTok{\# robust center/covariance via MCD}
\NormalTok{md\_robust }\OtherTok{\textless{}{-}} \FunctionTok{mahalanobis}\NormalTok{(}
\NormalTok{  num\_vars,                              }\CommentTok{\# data matrix}
  \AttributeTok{center =}\NormalTok{ cmcd}\SpecialCharTok{$}\NormalTok{center,                  }\CommentTok{\# robust center}
  \AttributeTok{cov =}\NormalTok{ cmcd}\SpecialCharTok{$}\NormalTok{cov                         }\CommentTok{\# robust covariance}
\NormalTok{)}

\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))                     }\CommentTok{\# two plots side by side}
\FunctionTok{plot}\NormalTok{(md\_classic, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{, }\AttributeTok{main =} \StringTok{"Mahalanobis (classic)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Distance"}\NormalTok{)  }\CommentTok{\# classic distances}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =}\NormalTok{ cutoff, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)                                       }\CommentTok{\# cutoff line}

\FunctionTok{plot}\NormalTok{(md\_robust, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{, }\AttributeTok{main =} \StringTok{"Mahalanobis (robust MCD)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Distance"}\NormalTok{) }\CommentTok{\# robust distances}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =}\NormalTok{ cutoff, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)                                       }\CommentTok{\# cutoff line}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-7-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))                     }\CommentTok{\# reset layout}

\NormalTok{flag\_classic }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(md\_classic }\SpecialCharTok{\textgreater{}}\NormalTok{ cutoff)    }\CommentTok{\# indices flagged by classic distance}
\NormalTok{flag\_robust  }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(md\_robust  }\SpecialCharTok{\textgreater{}}\NormalTok{ cutoff)    }\CommentTok{\# indices flagged by robust distance}

\NormalTok{out\_table }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(                            }\CommentTok{\# collect flagged machines}
  \AttributeTok{classical =} \FunctionTok{data.frame}\NormalTok{(                                       }\CommentTok{\# classic flagged table}
    \AttributeTok{machine =}\NormalTok{ machines\_sub}\SpecialCharTok{$}\NormalTok{machine[flag\_classic],       }\CommentTok{\# names flagged (classic)}
    \AttributeTok{distance =} \FunctionTok{round}\NormalTok{(md\_classic[flag\_classic], }\DecValTok{2}\NormalTok{)       }\CommentTok{\# classic distances}
\NormalTok{  ),}
  \AttributeTok{robust =} \FunctionTok{data.frame}\NormalTok{(                                          }\CommentTok{\# robust flagged table}
    \AttributeTok{machine =}\NormalTok{ machines\_sub}\SpecialCharTok{$}\NormalTok{machine[flag\_robust],        }\CommentTok{\# names flagged (robust)}
    \AttributeTok{distance =} \FunctionTok{round}\NormalTok{(md\_robust[flag\_robust], }\DecValTok{2}\NormalTok{)         }\CommentTok{\# robust distances}
\NormalTok{  )}
\NormalTok{)}
\NormalTok{out\_table                                   }\CommentTok{\# show both tables}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
$classical
             machine distance
1 honeywell-dps:6/96    22.52
2         ibm-3033:u    26.82
3           ibm-3081    23.13
4         ibm-3081:d    23.20
5         ibm-3083:b    19.11

$robust
              machine distance
1          hp-3000/88    53.08
2          harris-500    84.00
3          harris-700    68.59
4          harris-800    55.64
5  honeywell-dps:6/92    57.81
6  honeywell-dps:6/96   457.28
7  honeywell-dps:8/49  3358.27
8  honeywell-dps:8/50    70.90
9  honeywell-dps:8/52  3735.66
10 honeywell-dps:8/62  3548.44
11         ibm-3033:s   251.33
12         ibm-3033:u  3560.00
13           ibm-3081 34503.70
14         ibm-3081:d 30566.21
15         ibm-3083:b  8342.78
16         ibm-3083:e  1213.99
\end{verbatim}

Interpretation: both classic and robust distances keep most machines
below the 97.5\% cutoff (≈17.5), showing a fairly homogeneous core of
machines around a single multivariate centre. A smaller group lies above
the cutoff in at least one of the two metrics; these correspond to
atypical combinations of cycle time, memory, cache and channels. The
robust MCD distances sometimes flag a slightly different set because
they estimate centre and scatter after downweighting potential outliers,
which is desirable when searching for systematically atypical
configurations.

\subsubsection{Who is flagged and which variables drive
them?}\label{who-is-flagged-and-which-variables-drive-them}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{flagged\_ids }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(}\FunctionTok{c}\NormalTok{(flag\_classic, flag\_robust))   }\CommentTok{\# union of flagged indices}

\NormalTok{center\_c }\OtherTok{\textless{}{-}} \FunctionTok{colMeans}\NormalTok{(num\_vars)                        }\CommentTok{\# classic center}
\NormalTok{scale\_c }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diag}\NormalTok{(S\_classic))                      }\CommentTok{\# classic scales (SDs)}
\NormalTok{center\_r }\OtherTok{\textless{}{-}}\NormalTok{ cmcd}\SpecialCharTok{$}\NormalTok{center                               }\CommentTok{\# robust center}
\NormalTok{scale\_r }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diag}\NormalTok{(cmcd}\SpecialCharTok{$}\NormalTok{cov))                       }\CommentTok{\# robust scales (SDs)}

\CommentTok{\# Approximate per{-}variable contributions: squared standardized deviations (ignores correlation structure)}
\NormalTok{contrib\_mat\_classic }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{apply}\NormalTok{(num\_vars[flagged\_ids, ], }\DecValTok{1}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) ((x }\SpecialCharTok{{-}}\NormalTok{ center\_c) }\SpecialCharTok{/}\NormalTok{ scale\_c)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{contrib\_mat\_robust  }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{apply}\NormalTok{(num\_vars[flagged\_ids, ], }\DecValTok{1}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) ((x }\SpecialCharTok{{-}}\NormalTok{ center\_r) }\SpecialCharTok{/}\NormalTok{ scale\_r)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\FunctionTok{rownames}\NormalTok{(contrib\_mat\_classic) }\OtherTok{\textless{}{-}}\NormalTok{ machines\_sub}\SpecialCharTok{$}\NormalTok{machine[flagged\_ids]  }\CommentTok{\# label rows}
\FunctionTok{rownames}\NormalTok{(contrib\_mat\_robust)  }\OtherTok{\textless{}{-}}\NormalTok{ machines\_sub}\SpecialCharTok{$}\NormalTok{machine[flagged\_ids]}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \FunctionTok{seq\_along}\NormalTok{(flagged\_ids)) \{                   }\CommentTok{\# loop each flagged machine}
\NormalTok{  mid }\OtherTok{\textless{}{-}}\NormalTok{ machines\_sub}\SpecialCharTok{$}\NormalTok{machine[flagged\_ids[i]]         }\CommentTok{\# machine name}
\NormalTok{  op }\OtherTok{\textless{}{-}} \FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{), }\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{1}\NormalTok{))     }\CommentTok{\# two barplots side by side}
  \FunctionTok{barplot}\NormalTok{(contrib\_mat\_classic[i, ], }\AttributeTok{main =} \FunctionTok{paste}\NormalTok{(mid, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{classic z\^{}2"}\NormalTok{), }\AttributeTok{las =} \DecValTok{2}\NormalTok{, }\AttributeTok{cex.names =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"contrib"}\NormalTok{)  }\CommentTok{\# classic contributions}
  \FunctionTok{barplot}\NormalTok{(contrib\_mat\_robust[i, ],  }\AttributeTok{main =} \FunctionTok{paste}\NormalTok{(mid, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{robust z\^{}2"}\NormalTok{),  }\AttributeTok{las =} \DecValTok{2}\NormalTok{, }\AttributeTok{cex.names =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"contrib"}\NormalTok{)  }\CommentTok{\# robust contributions}
  \FunctionTok{par}\NormalTok{(op)                                             }\CommentTok{\# reset par}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-2.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-3.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-4.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-5.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-6.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-7.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-8.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-9.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-10.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-11.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-12.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-13.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-14.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-15.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-8-16.pdf}}

Interpretation guide: - These barplots show which variables have the
largest squared standardized deviations for each flagged machine (left:
classical center/scale; right: robust center/scale). - Large bars point
to the specs driving the outlying Mahalanobis distance (e.g., unusually
high memory, channels, or performance). - Robust scaling tempers the
influence of the bulk; if a bar stays large in both panels, that
variable is a consistent driver of atypicality.

Friendly readout of three examples:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{examples }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"honeywell{-}dps:6/96"}\NormalTok{, }\StringTok{"ibm{-}3081"}\NormalTok{, }\StringTok{"honeywell{-}dps:8/49"}\NormalTok{)  }\CommentTok{\# pick 3 machines}
\NormalTok{get\_top }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(mat, id, }\AttributeTok{k =} \DecValTok{3}\NormalTok{) \{                                  }\CommentTok{\# helper to grab top k contributions}
  \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\NormalTok{id }\SpecialCharTok{\%in\%} \FunctionTok{rownames}\NormalTok{(mat)) }\FunctionTok{return}\NormalTok{(}\ConstantTok{NA}\NormalTok{)                               }\CommentTok{\# handle missing}
  \FunctionTok{sort}\NormalTok{(mat[id, ], }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{k]                              }\CommentTok{\# largest k entries}
\NormalTok{\}}
\NormalTok{example\_top }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(examples, }\ControlFlowTok{function}\NormalTok{(id) \{                         }\CommentTok{\# build list for each example}
  \FunctionTok{list}\NormalTok{(}
    \AttributeTok{machine =}\NormalTok{ id,                                                      }\CommentTok{\# machine name}
    \AttributeTok{classic\_top =} \FunctionTok{round}\NormalTok{(}\FunctionTok{get\_top}\NormalTok{(contrib\_mat\_classic, id), }\DecValTok{2}\NormalTok{),          }\CommentTok{\# top classic contributors}
    \AttributeTok{robust\_top =} \FunctionTok{round}\NormalTok{(}\FunctionTok{get\_top}\NormalTok{(contrib\_mat\_robust, id), }\DecValTok{2}\NormalTok{)             }\CommentTok{\# top robust contributors}
\NormalTok{  )}
\NormalTok{\})}
\NormalTok{example\_top                                                            }\CommentTok{\# show the list}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[[1]]
[[1]]$machine
[1] "honeywell-dps:6/96"

[[1]]$classic_top
CHMAX  MMAX  MMIN 
16.75  0.34  0.16 

[[1]]$robust_top
CHMAX  MMAX   ERP 
83.25 31.21 26.10 


[[2]]
[[2]]$machine
[1] "ibm-3081"

[[2]]$classic_top
 MMIN CHMIN   PRP 
14.49 14.32 12.51 

[[2]]$robust_top
    ERP     PRP    MMIN 
1306.96  738.67  229.00 


[[3]]
[[3]]$machine
[1] "honeywell-dps:8/49"

[[3]]$classic_top
MMAX  ERP CACH 
4.39 1.55 1.45 

[[3]]$robust_top
   ERP   MMAX    PRP 
259.32 159.27  44.41 
\end{verbatim}

\begin{itemize}
\tightlist
\item
  \texttt{honeywell-dps:6/96}: dominated by very high \texttt{CHMAX}
  (channels), with moderate influence from \texttt{MMAX} and
  \texttt{ERP} in the robust view.
\item
  \texttt{ibm-3081}: extreme across memory (\texttt{MMIN},
  \texttt{MMAX}), cache, and performance (\texttt{PRP}, \texttt{ERP}),
  especially in the robust scaling where these dwarfish deviations
  inflate the distance.
\item
  \texttt{honeywell-dps:8/49}: stands out for large \texttt{MMAX} and
  \texttt{CACH}, coupled with higher \texttt{PRP}/\texttt{ERP} relative
  to the robust center.
\end{itemize}

\subsection{Summary of the preliminary
analysis}\label{summary-of-the-preliminary-analysis}

Overall, the subset contains 41 machines with heterogeneous hardware
characteristics (\texttt{MMIN}, \texttt{MMAX}, \texttt{CACH}, channel
counts and performance metrics). The comparison between mean, median,
trimmed and winsorized means, together with the MAD values, highlights
variables where the bulk of the data is concentrated but a few machines
deviate substantially from the main group. The covariance matrix and
Mahalanobis distances confirm this picture: most observations form a
compact cloud near a common centre, while a small number of models, such
as \texttt{honeywell-dps:6/96}, \texttt{ibm-3081} and
\texttt{honeywell-dps:8/49}, display unusually large memory, cache and
performance values and are flagged as multivariate outliers.

This preliminary step already suggests a dominant ``size/performance''
gradient in the data, ranging from modest systems to high-end machines.
This motivates the use of PCA in the next section to summarise that
multivariate structure with a reduced number of components while
retaining most of the total variance.

\section{Principal Component Analysis (original vs
standardized)}\label{principal-component-analysis-original-vs-standardized}

We compare PCA on raw scales (keeps original units) vs standardized
(puts variables on equal footing).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pca\_raw }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(num\_vars, }\AttributeTok{center =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{scale. =} \ConstantTok{FALSE}\NormalTok{)   }\CommentTok{\# PCA on raw scale}
\NormalTok{pca\_std }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(num\_vars, }\AttributeTok{center =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{scale. =} \ConstantTok{TRUE}\NormalTok{)    }\CommentTok{\# PCA on standardized data}

\CommentTok{\# ensure numeric to avoid class quirks on sdev}
\NormalTok{sdev\_raw }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(pca\_raw}\SpecialCharTok{$}\NormalTok{sdev)                         }\CommentTok{\# SDs of PCs (raw)}
\NormalTok{sdev\_std }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(pca\_std}\SpecialCharTok{$}\NormalTok{sdev)                         }\CommentTok{\# SDs of PCs (std)}

\NormalTok{pve\_raw }\OtherTok{\textless{}{-}}\NormalTok{ sdev\_raw}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(sdev\_raw}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)                      }\CommentTok{\# proportion variance explained (raw)}
\NormalTok{pve\_std }\OtherTok{\textless{}{-}}\NormalTok{ sdev\_std}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(sdev\_std}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)                      }\CommentTok{\# proportion variance explained (std)}
\end{Highlighting}
\end{Shaded}

\subsection{Scree plots and variance
explained}\label{scree-plots-and-variance-explained}

Red line marks 95\% cumulative variance target.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))                                          }\CommentTok{\# side{-}by{-}side scree plots}
\FunctionTok{plot}\NormalTok{(pve\_raw }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\AttributeTok{type =} \StringTok{"b"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"PC"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"\% variance"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Raw scale"}\NormalTok{)                                      }\CommentTok{\# raw PVE}
\FunctionTok{lines}\NormalTok{(}\FunctionTok{cumsum}\NormalTok{(pve\_raw) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\AttributeTok{type =} \StringTok{"b"}\NormalTok{, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{)        }\CommentTok{\# cumulative PVE (raw)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{95}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)                          }\CommentTok{\# 95\% line}

\FunctionTok{plot}\NormalTok{(pve\_std }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\AttributeTok{type =} \StringTok{"b"}\NormalTok{, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"PC"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"\% variance"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Standardized"}\NormalTok{)                                   }\CommentTok{\# standardized PVE}
\FunctionTok{lines}\NormalTok{(}\FunctionTok{cumsum}\NormalTok{(pve\_std) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\AttributeTok{type =} \StringTok{"b"}\NormalTok{, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{)        }\CommentTok{\# cumulative PVE (std)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{95}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)                          }\CommentTok{\# 95\% line}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-11-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))                                          }\CommentTok{\# reset layout}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{k\_raw }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{cumsum}\NormalTok{(pve\_raw) }\SpecialCharTok{\textgreater{}=} \FloatTok{0.95}\NormalTok{)[}\DecValTok{1}\NormalTok{]                    }\CommentTok{\# PCs needed (raw) for 95\%}
\NormalTok{k\_std }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{cumsum}\NormalTok{(pve\_std) }\SpecialCharTok{\textgreater{}=} \FloatTok{0.95}\NormalTok{)[}\DecValTok{1}\NormalTok{]                    }\CommentTok{\# PCs needed (std) for 95\%}

\FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{scale =} \FunctionTok{c}\NormalTok{(}\StringTok{"raw"}\NormalTok{, }\StringTok{"standardized"}\NormalTok{),                           }\CommentTok{\# scale type}
  \AttributeTok{pcs\_needed\_for\_95pct =} \FunctionTok{c}\NormalTok{(k\_raw, k\_std),                     }\CommentTok{\# count of PCs to reach 95\%}
  \AttributeTok{cumulative\_variance =} \FunctionTok{c}\NormalTok{(}\FunctionTok{cumsum}\NormalTok{(pve\_raw)[k\_raw], }\FunctionTok{cumsum}\NormalTok{(pve\_std)[k\_std])  }\CommentTok{\# achieved cum PVE}
\NormalTok{)                                                           }\CommentTok{\# show summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
         scale pcs_needed_for_95pct cumulative_variance
1          raw                    2           0.9994522
2 standardized                    5           0.9724443
\end{verbatim}

Interpretation: - Raw-scale PCA reaches ≥95\% variance with 2
components; standardized PCA does so with 5. Because variables are on
different units (ns vs KB vs counts vs performance), the standardized
solution is the safer, more interpretable default. - The first
standardized PC loads heavily (in magnitude) on memory and performance
(\texttt{MMAX}, \texttt{MMIN}, \texttt{PRP}, \texttt{ERP}, plus
\texttt{CACH}), so it summarizes overall ``capacity/performance.'' PC2
contrasts channel capacity (\texttt{CHMAX}) against cycle time and
minimum channels, hinting at an I/O vs speed axis. - In other words,
most of the multivariate variability can be compressed into the first
few standardized components: with only 5 PCs we already achieve at least
95\% of the total variance, which is a substantial reduction from the
original 8 dimensions. - Recommendation: for dimension reduction we
report the standardized PCA and retain the first 5 components (≥95\%
variance), interpreting PC1 as a scale of overall performance/memory and
PC2 as a channels vs speed dimension; the remaining retained PCs mostly
capture finer contrasts between already powerful machines.

\subsection{Loadings and interpretation
aids}\label{loadings-and-interpretation-aids}

Inspect which variables drive the first PCs (signs may flip without
changing interpretation).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(pca\_raw}\SpecialCharTok{$}\NormalTok{rotation[, }\DecValTok{1}\SpecialCharTok{:}\FunctionTok{min}\NormalTok{(}\DecValTok{3}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(num\_vars))])  }\CommentTok{\# raw loadings (first PCs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                PC1           PC2           PC3
MYCT   0.0141412358 -0.0077399303  0.9994839149
MMIN  -0.2286221980  0.9731769922  0.0106566935
MMAX  -0.9733452865 -0.2289360796  0.0119681990
CACH  -0.0012202199  0.0012445172  0.0001322595
CHMIN -0.0001606719  0.0006590092 -0.0020541284
CHMAX -0.0007701548 -0.0025019794 -0.0219924018
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(pca\_std}\SpecialCharTok{$}\NormalTok{rotation[, }\DecValTok{1}\SpecialCharTok{:}\FunctionTok{min}\NormalTok{(}\DecValTok{3}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(num\_vars))])  }\CommentTok{\# standardized loadings (first PCs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
             PC1         PC2         PC3
MYCT   0.2609775 -0.39938737 -0.72811374
MMIN  -0.3860768 -0.28892323  0.06954451
MMAX  -0.3871015  0.16725096 -0.28349782
CACH  -0.3699990  0.01382335 -0.32360056
CHMIN -0.3328552 -0.25326137  0.45179763
CHMAX -0.1386368  0.79963560 -0.15685676
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top\_loadings }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(rot, }\AttributeTok{pcs =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{, }\AttributeTok{k =} \DecValTok{3}\NormalTok{) \{              }\CommentTok{\# helper to grab top loadings}
  \FunctionTok{do.call}\NormalTok{(rbind, }\FunctionTok{lapply}\NormalTok{(pcs, }\ControlFlowTok{function}\NormalTok{(j) \{          }\CommentTok{\# loop over PCs of interest}
\NormalTok{    ord }\OtherTok{\textless{}{-}} \FunctionTok{order}\NormalTok{(}\FunctionTok{abs}\NormalTok{(rot[, j]), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)[}\FunctionTok{seq\_len}\NormalTok{(k)]  }\CommentTok{\# top k by abs loading}
    \FunctionTok{data.frame}\NormalTok{(}
      \AttributeTok{PC =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"PC"}\NormalTok{, j),                          }\CommentTok{\# which PC}
      \AttributeTok{variable =} \FunctionTok{rownames}\NormalTok{(rot)[ord],                 }\CommentTok{\# variable name}
      \AttributeTok{loading =} \FunctionTok{round}\NormalTok{(rot[ord, j], }\DecValTok{3}\NormalTok{),               }\CommentTok{\# signed loading}
      \AttributeTok{abs\_loading =} \FunctionTok{round}\NormalTok{(}\FunctionTok{abs}\NormalTok{(rot[ord, j]), }\DecValTok{3}\NormalTok{)       }\CommentTok{\# absolute loading}
\NormalTok{    )}
\NormalTok{  \}))}
\NormalTok{\}}

\NormalTok{top\_std }\OtherTok{\textless{}{-}} \FunctionTok{top\_loadings}\NormalTok{(pca\_std}\SpecialCharTok{$}\NormalTok{rotation, }\AttributeTok{pcs =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{, }\AttributeTok{k =} \DecValTok{4}\NormalTok{)   }\CommentTok{\# top 4 for std PCs 1{-}2}
\NormalTok{top\_raw }\OtherTok{\textless{}{-}} \FunctionTok{top\_loadings}\NormalTok{(pca\_raw}\SpecialCharTok{$}\NormalTok{rotation, }\AttributeTok{pcs =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{, }\AttributeTok{k =} \DecValTok{4}\NormalTok{)   }\CommentTok{\# top 4 for raw PCs 1{-}2}
\FunctionTok{list}\NormalTok{(                                                          }\CommentTok{\# bundle for printing}
  \AttributeTok{top\_loadings\_standardized =}\NormalTok{ top\_std,                        }\CommentTok{\# report std top loadings}
  \AttributeTok{top\_loadings\_raw =}\NormalTok{ top\_raw                                  }\CommentTok{\# report raw top loadings}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
$top_loadings_standardized
       PC variable loading abs_loading
PRP   PC1      PRP  -0.429       0.429
ERP   PC1      ERP  -0.427       0.427
MMAX  PC1     MMAX  -0.387       0.387
MMIN  PC1     MMIN  -0.386       0.386
CHMAX PC2    CHMAX   0.800       0.800
MYCT  PC2     MYCT  -0.399       0.399
MMIN1 PC2     MMIN  -0.289       0.289
CHMIN PC2    CHMIN  -0.253       0.253

$top_loadings_raw
       PC variable loading abs_loading
MMAX  PC1     MMAX  -0.973       0.973
MMIN  PC1     MMIN  -0.229       0.229
MYCT  PC1     MYCT   0.014       0.014
PRP   PC1      PRP  -0.009       0.009
MMIN1 PC2     MMIN   0.973       0.973
MMAX1 PC2     MMAX  -0.229       0.229
PRP1  PC2      PRP   0.019       0.019
ERP   PC2      ERP   0.010       0.010
\end{verbatim}

\subsection{Scores plot (first two
PCs)}\label{scores-plot-first-two-pcs}

Use labels to spot grouping and extremes; standardized version is shown
here.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scores\_std }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(pca\_std}\SpecialCharTok{$}\NormalTok{x)                    }\CommentTok{\# PCA scores (std)}
\NormalTok{scores\_std}\SpecialCharTok{$}\NormalTok{machine }\OtherTok{\textless{}{-}}\NormalTok{ machines\_sub}\SpecialCharTok{$}\NormalTok{machine               }\CommentTok{\# add machine names}

\FunctionTok{plot}\NormalTok{(scores\_std}\SpecialCharTok{$}\NormalTok{PC1, scores\_std}\SpecialCharTok{$}\NormalTok{PC2, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{,           }\CommentTok{\# scatter of PC1 vs PC2}
     \AttributeTok{xlab =} \StringTok{"PC1 (std)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"PC2 (std)"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Scores on standardized data"}\NormalTok{)}
\FunctionTok{text}\NormalTok{(scores\_std}\SpecialCharTok{$}\NormalTok{PC1, scores\_std}\SpecialCharTok{$}\NormalTok{PC2, }\AttributeTok{labels =}\NormalTok{ scores\_std}\SpecialCharTok{$}\NormalTok{machine,}
     \AttributeTok{pos =} \DecValTok{3}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.6}\NormalTok{)                                 }\CommentTok{\# label points}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-15-1.pdf}}

Interpretation: the standardized score plot shows where machines align
along the performance/memory axis (PC1) and the channels-vs-speed axis
(PC2). Machines far to the right on PC1 have higher memory and
performance ratings, whereas the vertical spread reflects different
channel configurations relative to cycle time. Labels make it easy to
relate extreme scores back to specific models when discussing results.

\section{Outlier experiment}\label{outlier-experiment}

Introduce the atypical point at the former \texttt{hp-3000/64} row (no
standardization).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xnew }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{75}\NormalTok{, }\DecValTok{2000}\NormalTok{, }\FloatTok{0.8}\NormalTok{, }\DecValTok{80000}\NormalTok{, }\DecValTok{300}\NormalTok{, }\DecValTok{24}\NormalTok{, }\DecValTok{62}\NormalTok{, }\DecValTok{47}\NormalTok{)          }\CommentTok{\# injected outlier values}
\NormalTok{machines\_out }\OtherTok{\textless{}{-}}\NormalTok{ machines\_sub                              }\CommentTok{\# start from subset}
\NormalTok{machines\_out[machines\_out}\SpecialCharTok{$}\NormalTok{machine }\SpecialCharTok{==} \StringTok{"hp{-}3000/64"}\NormalTok{, }\FunctionTok{names}\NormalTok{(num\_vars)] }\OtherTok{\textless{}{-}}\NormalTok{ xnew  }\CommentTok{\# replace row}

\NormalTok{pca\_out\_classic }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(machines\_out[}\FunctionTok{names}\NormalTok{(num\_vars)], }\AttributeTok{center =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{scale. =} \ConstantTok{FALSE}\NormalTok{)   }\CommentTok{\# classic PCA with outlier}
\NormalTok{pca\_out\_robust }\OtherTok{\textless{}{-}} \FunctionTok{PcaCov}\NormalTok{(machines\_out[}\FunctionTok{names}\NormalTok{(num\_vars)], }\AttributeTok{cov.control =} \FunctionTok{CovControlMcd}\NormalTok{(), }\AttributeTok{scale =} \ConstantTok{FALSE}\NormalTok{)  }\CommentTok{\# robust PCA}

\NormalTok{pve\_out\_classic }\OtherTok{\textless{}{-}}\NormalTok{ pca\_out\_classic}\SpecialCharTok{$}\NormalTok{sdev}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(pca\_out\_classic}\SpecialCharTok{$}\NormalTok{sdev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)  }\CommentTok{\# PVE classic}
\NormalTok{pve\_out\_robust }\OtherTok{\textless{}{-}}\NormalTok{ pca\_out\_robust}\SpecialCharTok{@}\NormalTok{eigenvalues }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(pca\_out\_robust}\SpecialCharTok{@}\NormalTok{eigenvalues)  }\CommentTok{\# PVE robust}

\FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{component =} \FunctionTok{seq\_along}\NormalTok{(pve\_out\_classic),                 }\CommentTok{\# component index}
  \AttributeTok{classic\_pct =} \FunctionTok{round}\NormalTok{(pve\_out\_classic }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{),          }\CommentTok{\# classic PVE (\%)}
  \AttributeTok{robust\_pct =} \FunctionTok{round}\NormalTok{(pve\_out\_robust }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{)             }\CommentTok{\# robust PVE (\%)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
  component classic_pct robust_pct
1         1       57.96      89.76
2         2       39.58       7.87
3         3        2.44       2.36
4         4        0.02       0.00
5         5        0.00       0.00
6         6        0.00       0.00
7         7        0.00       0.00
8         8        0.00       0.00
\end{verbatim}

This table allows us to compare how the injected outlier redistributes
the variance across components under the classical and robust
approaches. In the classical PCA, the first eigenvalue typically
inflates and captures a very large share of the variance because the
outlier dominates the covariance structure. In contrast, the robust
eigenvalues stay closer to what we observed without the outlier, meaning
that the bulk geometry is preserved.

\subsection{Visual comparison: scores}\label{visual-comparison-scores}

Outlier effect: in classical PCA, the first axis often aligns with the
extreme point; robust PCA should stay closer to the bulk structure.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))                                       }\CommentTok{\# two plots}
\FunctionTok{plot}\NormalTok{(pca\_out\_classic}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{1}\NormalTok{], pca\_out\_classic}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{2}\NormalTok{], }\AttributeTok{pch =} \DecValTok{19}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Classic PCA with outlier"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"PC1"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"PC2"}\NormalTok{)  }\CommentTok{\# classic scores}
\FunctionTok{text}\NormalTok{(pca\_out\_classic}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{1}\NormalTok{], pca\_out\_classic}\SpecialCharTok{$}\NormalTok{x[,}\DecValTok{2}\NormalTok{],}
     \AttributeTok{labels =}\NormalTok{ machines\_out}\SpecialCharTok{$}\NormalTok{machine, }\AttributeTok{pos =} \DecValTok{3}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.5}\NormalTok{)              }\CommentTok{\# labels}

\FunctionTok{plot}\NormalTok{(pca\_out\_robust}\SpecialCharTok{@}\NormalTok{scores[,}\DecValTok{1}\NormalTok{], pca\_out\_robust}\SpecialCharTok{@}\NormalTok{scores[,}\DecValTok{2}\NormalTok{], }\AttributeTok{pch =} \DecValTok{19}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Robust PCA (MCD)"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"PC1"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"PC2"}\NormalTok{)          }\CommentTok{\# robust scores}
\FunctionTok{text}\NormalTok{(pca\_out\_robust}\SpecialCharTok{@}\NormalTok{scores[,}\DecValTok{1}\NormalTok{], pca\_out\_robust}\SpecialCharTok{@}\NormalTok{scores[,}\DecValTok{2}\NormalTok{],}
     \AttributeTok{labels =}\NormalTok{ machines\_out}\SpecialCharTok{$}\NormalTok{machine, }\AttributeTok{pos =} \DecValTok{3}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.5}\NormalTok{)              }\CommentTok{\# labels}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-17-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))                                       }\CommentTok{\# reset layout}
\end{Highlighting}
\end{Shaded}

\subsubsection{Distance diagnostics (robust
PCA)}\label{distance-diagnostics-robust-pca}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(pca\_out\_robust)  }\CommentTok{\# outlier map: orthogonal vs score distances}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/unnamed-chunk-18-1.pdf}}

\section{Decisions}\label{decisions}

\begin{itemize}
\tightlist
\item
  For exploratory analysis we rely on classical summaries to describe
  central tendency and spread, but interpret them in parallel with
  robust statistics (trimmed and winsorized means, MAD and MCD-based
  Mahalanobis distances) to avoid being misled by a few extreme
  machines.
\item
  For dimension reduction we base our decision on the proportion of
  variance explained and interpretability of the loadings: we favour the
  standardized PCA and retain the first 5 principal components, which
  already explain at least 95\% of the total variance in the eight
  numeric variables.
\item
  When a single atypical observation is present, we use robust PCA based
  on the MCD covariance estimate to describe the multivariate structure
  of the bulk of the data, and treat the classical PCA mainly as a
  diagnostic to illustrate the effect of the outlier.
\end{itemize}

\section{Conclusions}\label{conclusions}

The subset of \texttt{machines} data considered here exhibits a clear
gradient from low to high capability systems, mainly driven by memory
size, cache and performance measures. The preliminary analysis using
classical and robust summaries, together with Mahalanobis distances,
shows that most machines cluster around a central configuration while a
small number of high-end models stand out as multivariate outliers.

Standardized PCA provides an effective summary of this structure: with
only 5 components we retain at least 95\% of the total variance and
obtain interpretable directions, where the first component captures an
overall performance/memory level and the second contrasts channel
capacity with speed. Plotting the scores on these components reveals how
specific named machines occupy different regions of the
performance--channels trade-off.

After injecting the artificial outlier, classical PCA becomes strongly
influenced by this single observation, reallocating a large share of
variance to the first component and distorting the geometry of the
remaining points. In contrast, the MCD-based robust PCA keeps the
eigenvalues and loading patterns closer to the original analysis and
clearly isolates the modified machine in the outlier map. This
comparison illustrates the vulnerability of classical PCA to even one
atypical observation and motivates the use of robust methods when data
contamination is plausible.

\section{Bibliography}\label{bibliography}

\begin{itemize}
\tightlist
\item
  Jolliffe, I. T. (2002). \emph{Principal Component Analysis}. Springer.
\item
  Todorov, V., \& Filzmoser, P. (2009). An object oriented framework for
  robust multivariate analysis. \emph{Journal of Statistical Software},
  32(3), 1--47. ***
\end{itemize}




\end{document}
